/**
 * Example: Hono CRUD with Drizzle ORM and PostgreSQL
 *
 * Run with:
 * 1. docker compose up -d
 * 2. npx tsx examples/postgres.ts
 */

import { Hono, type Env } from 'hono';
import { serve } from '@hono/node-server';
import { z } from 'zod';
import { pgTable, text, integer, timestamp, uuid } from 'drizzle-orm/pg-core';
import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import { fromHono, registerCrud, setupSwaggerUI, setupReDoc, defineModel, defineMeta } from '../src/index.js';
import {
  DrizzleCreateEndpoint,
  DrizzleReadEndpoint,
  DrizzleUpdateEndpoint,
  DrizzleDeleteEndpoint,
  DrizzleListEndpoint,
  type DrizzleDatabase,
} from '../src/adapters/drizzle/index.js';

const { Pool } = pg;

// PostgreSQL connection
const pool = new Pool({
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT) || 5432,
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_NAME || 'hono_crud',
});

// Create Drizzle instance
const db = drizzle(pool);

// Define the Drizzle table schema for PostgreSQL
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  name: text('name').notNull(),
  role: text('role', { enum: ['admin', 'user'] }).notNull().default('user'),
  age: integer('age'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Define Zod schema for validation
// Note: id and createdAt are optional because they're auto-generated by the database
const UserSchema = z.object({
  id: z.string().uuid().optional(),
  email: z.string().email(),
  name: z.string().min(1),
  role: z.enum(['admin', 'user']).default('user'),
  age: z.number().int().positive().optional().nullable(),
  createdAt: z.date().optional(),
});

type User = z.infer<typeof UserSchema>;

// Create the model configuration using type-safe helper
const UserModel = defineModel({
  tableName: 'users',
  schema: UserSchema,
  primaryKeys: ['id'],
  table: users, // Link to Drizzle table
});

// Meta configuration using type-safe helper
const userMeta = defineMeta({
  model: UserModel,
});

// Cast db once to DrizzleDatabase for type safety
const typedDb = db as unknown as DrizzleDatabase;

// Create Endpoints - TypeScript infers types from _meta
class UserCreate extends DrizzleCreateEndpoint {
  _meta = userMeta;
  db = typedDb;

  schema = {
    tags: ['Users'],
    summary: 'Create a new user',
  };
}

class UserList extends DrizzleListEndpoint {
  _meta = userMeta;
  db = typedDb;

  schema = {
    tags: ['Users'],
    summary: 'List all users',
  };

  // Configure filtering, searching, and sorting
  filterFields = ['role'];
  filterConfig = {
    age: ['eq', 'gt', 'gte', 'lt', 'lte', 'between'] as const,
  };
  searchFields = ['name', 'email'];
  orderByFields = ['name', 'createdAt', 'age'];
  defaultOrderBy = 'createdAt';
  defaultOrderDirection: 'asc' | 'desc' = 'desc';
}

class UserRead extends DrizzleReadEndpoint {
  _meta = userMeta;
  db = typedDb;

  schema = {
    tags: ['Users'],
    summary: 'Get a user by ID',
  };
}

class UserUpdate extends DrizzleUpdateEndpoint {
  _meta = userMeta;
  db = typedDb;

  schema = {
    tags: ['Users'],
    summary: 'Update a user',
  };

  // Only allow updating these fields
  allowedUpdateFields = ['name', 'role', 'age'];
}

class UserDelete extends DrizzleDeleteEndpoint {
  _meta = userMeta;
  db = typedDb;

  schema = {
    tags: ['Users'],
    summary: 'Delete a user',
  };
}

// Create the app
const app = fromHono(new Hono());

// Register all CRUD endpoints for /users - no more `as any` needed!
registerCrud(app, '/users', {
  create: UserCreate,
  list: UserList,
  read: UserRead,
  update: UserUpdate,
  delete: UserDelete,
});

// Setup OpenAPI documentation
app.doc('/openapi.json', {
  openapi: '3.1.0',
  info: {
    title: 'User API with PostgreSQL',
    version: '1.0.0',
    description: 'A full CRUD API for users using Hono, Drizzle ORM, and PostgreSQL',
  },
});

// Swagger UI and ReDoc
setupSwaggerUI(app, { docsPath: '/docs', specPath: '/openapi.json' });
setupReDoc(app, { redocPath: '/redoc', specPath: '/openapi.json', title: 'User API with PostgreSQL' });

// Health check endpoint
app.get('/health', (c) => c.json({ status: 'ok' }));

// Initialize database
async function initDb() {
  // Create table if not exists
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      email TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user',
      age INTEGER,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    )
  `);

  console.log('Database initialized');
}

// Start server
const port = Number(process.env.PORT) || 3456;

initDb()
  .then(() => {
    console.log(`Server running at http://localhost:${port}`);
    console.log(`OpenAPI docs at http://localhost:${port}/openapi.json`);
    console.log('');
    console.log('PostgreSQL connection:');
    console.log(`  Host: ${process.env.DB_HOST || 'localhost'}`);
    console.log(`  Port: ${process.env.DB_PORT || 5432}`);
    console.log(`  Database: ${process.env.DB_NAME || 'hono_crud'}`);
    console.log('');
    console.log('Available endpoints:');
    console.log('  POST   /users          - Create a user');
    console.log('  GET    /users          - List all users');
    console.log('  GET    /users/:id      - Get a user');
    console.log('  PATCH  /users/:id      - Update a user');
    console.log('  DELETE /users/:id      - Delete a user');

    serve({
      fetch: app.fetch,
      port,
    });
  })
  .catch((err) => {
    console.error('Failed to initialize database:', err);
    process.exit(1);
  });
